# Generated by Django 3.2.13 on 2022-07-24 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('last_location', models.CharField(blank=True, max_length=255)),
                ('created_location', models.CharField(blank=True, max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_managed', models.BooleanField(default=False)),
                ('is_password_expired', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_password_autoset', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('billing_address_country', models.CharField(default='INDIA', max_length=255)),
                ('billing_address', models.JSONField(null=True)),
                ('has_billing_address', models.BooleanField(default=False)),
                ('user_timezone', models.CharField(default='Asia/Kolkata', max_length=255)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('last_login_time', models.DateTimeField(null=True)),
                ('last_logout_time', models.DateTimeField(null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=255)),
                ('last_logout_ip', models.CharField(blank=True, max_length=255)),
                ('last_login_medium', models.CharField(default='email', max_length=20)),
                ('last_login_uagent', models.TextField(blank=True)),
                ('token_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=255)),
                ('description', models.JSONField(blank=True, null=True)),
                ('instructions', models.JSONField(blank=True, null=True)),
                ('cover_url', models.TextField(default=dict)),
                ('link', models.TextField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('kind', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('SEMI-ONLINE', 'SEMI-ONLINE')], default='ONLINE', max_length=255)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(default='DEFAULT', max_length=255)),
                ('description', models.JSONField(default=dict)),
                ('instructions', models.JSONField(default=dict)),
                ('is_timed', models.BooleanField(default=False)),
                ('time_limit', models.IntegerField(default=0)),
                ('tools', models.JSONField(default=dict)),
                ('pre_screen', models.JSONField(default=dict)),
                ('post_screen', models.JSONField(default=dict)),
                ('sequence', models.FloatField(default=0)),
                ('layout', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('timers', models.JSONField(default=dict)),
                ('bubble_sheet_data', models.JSONField(default=dict)),
                ('bubble_sheet_questions', models.JSONField(default=dict)),
                ('bubble_sheet_answers', models.JSONField(default=dict)),
                ('paragraphs', models.JSONField(default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sections', to='db.assessment')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('title', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('files', models.JSONField(default=dict)),
                ('timers', models.JSONField(default=dict)),
                ('assets', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('explanation', models.JSONField(default=dict)),
                ('feedback', models.TextField(default=dict)),
                ('type', models.CharField(choices=[('MCQ', 'MCQ'), ('FIB', 'FIB'), ('TF', 'TF'), ('FRQ', 'FRQ')], default='MCQ', max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('data', models.JSONField(default=dict)),
                ('blocks', models.JSONField(default=dict)),
                ('questions', models.JSONField(default=dict)),
                ('sequence', models.FloatField(default=0)),
                ('layout', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='db.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='db.assessmentsection')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('hash', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('sequence', models.FloatField(default=0)),
                ('assets', models.JSONField(default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='db.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
