# Generated by Django 3.2.13 on 2022-08-13 11:04

from django.db import migrations, models
import django.db.models.deletion
import zuperscore.db.models.library


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_subjectnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('asset', models.FileField(upload_to=zuperscore.db.models.library.get_file_upload_path)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('context', models.CharField(choices=[('library', 'Library'), ('exams', 'Exams'), ('subjects', 'Subjects'), ('users', 'users')], default='library', max_length=255)),
            ],
            options={
                'verbose_name': 'File Asset',
                'verbose_name_plural': 'File Assets',
                'db_table': 'library_assets',
            },
        ),
        migrations.CreateModel(
            name='QuestionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('data', models.JSONField(default=dict)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_nodes', to='db.subjectnode')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_nodes', to='db.question')),
            ],
            options={
                'unique_together': {('question', 'node')},
            },
        ),
    ]
