# Generated by Django 3.2.15 on 2022-09-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_fileasset_questionnode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('sequence',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelTable(
            name='option',
            table='options',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
