# Generated by Django 3.2.13 on 2022-10-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20220913_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('FIB', 'FIB'), ('TF', 'TF'), ('SPR', 'SPR')], default='MCQ', max_length=255),
        ),
    ]
