# Generated by Django 3.2.13 on 2022-11-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_assessments',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_assessments_completed',
            field=models.JSONField(null=True),
        ),
    ]
