# Generated by Django 3.2.15 on 2022-11-19 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_started', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_resumed', models.BooleanField(default=False)),
                ('is_restarted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('restarted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('total_incorrect', models.PositiveIntegerField(default=0)),
                ('total_unanswered', models.PositiveIntegerField(default=0)),
                ('total_attempted', models.PositiveIntegerField(default=0)),
                ('total_unattempted', models.PositiveIntegerField(default=0)),
                ('section_wise_data', models.JSONField(default=dict)),
                ('summary_data', models.JSONField(default=dict)),
                ('is_pscale_success', models.BooleanField(default=False)),
                ('pscale_data', models.JSONField(default=dict)),
                ('section_question_data', models.JSONField(default=dict)),
                ('section_info_data', models.JSONField(default=dict)),
                ('section_time_data', models.JSONField(default=dict)),
                ('section_marks_data', models.JSONField(default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment_sessions', to='db.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
