# Generated by Django 3.2.13 on 2022-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_userassessmentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsection',
            name='switching_route',
            field=models.JSONField(default=dict),
        ),
    ]
