# Generated by Django 3.2.13 on 2022-11-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_assessmentsection_switching_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsection',
            name='type',
            field=models.CharField(choices=[('STANDARD', 'STANDARD'), ('RANDOM', 'RANDOM'), ('ADAPTIVE', 'ADAPTIVE')], default='STANDARD', max_length=255),
        ),
    ]
