# Generated by Django 3.2.13 on 2022-11-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_assessmentsection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnode',
            name='sequence',
            field=models.FloatField(default=0),
        ),
    ]
