# Generated by Django 3.2.13 on 2022-12-10 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_alter_questionnode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approvers_difficulty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='blume_taxonomy',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='decision',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='irt_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='irt_b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='irt_c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='sourced_from',
            field=models.CharField(default='ZUPERSCORE', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='statistical_difficulty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='used_in',
            field=models.JSONField(default=dict),
        ),
    ]
