# Generated by Django 3.2.13 on 2022-12-10 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20221210_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
