# Generated by Django 3.2.13 on 2022-12-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_question_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('PRACTICE', 'PRACTICE'), ('MOCK', 'MOCK')], default='ONLINE', max_length=255),
        ),
    ]
