# Generated by Django 3.2.13 on 2022-12-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_alter_assessment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessmentsession',
            name='generated_by',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
