# Generated by Django 3.2.13 on 2023-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_userassessmentsession_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
