# Generated by Django 3.2.13 on 2023-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_question_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
