# Generated by Django 3.2.13 on 2023-01-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
