# Generated by Django 3.2.13 on 2023-02-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20230131_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessmentsession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userassessmentsession',
            name='state',
            field=models.CharField(choices=[('UNTOUCHED', 'UNTOUCHED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('ARCHIVED', 'ARCHIVED'), ('ANALYSED', 'ANALYSED'), ('REVIEWED', 'REVIEWED')], default='UNTOUCHED', max_length=255),
        ),
    ]
