# Generated by Django 3.2.13 on 2023-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20230213_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('MOCK', 'MOCK'), ('SECTIONAL', 'SECTIONAL'), ('MICRO', 'MICRO'), ('PRACTICE_SHEET', 'PRACTICE_SHEET'), ('DIAGNOSTIC', 'DIAGNOSTIC')], default='MOCK', max_length=255),
        ),
    ]
