# Generated by Django 3.2.13 on 2023-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_userattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
