# Generated by Django 3.2.13 on 2023-02-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_userattempt_is_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassessmentsession',
            old_name='section_wise_data',
            new_name='section_analysis_data',
        ),
        migrations.RenameField(
            model_name='userassessmentsession',
            old_name='summary_data',
            new_name='total_correct_qids',
        ),
        migrations.RemoveField(
            model_name='userassessmentsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userassessmentsession',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='userassessmentsession',
            name='is_restarted',
        ),
        migrations.RemoveField(
            model_name='userassessmentsession',
            name='is_resumed',
        ),
        migrations.RemoveField(
            model_name='userassessmentsession',
            name='paused_at',
        ),
        migrations.RemoveField(
            model_name='userassessmentsession',
            name='restarted_at',
        ),
        migrations.RemoveField(
            model_name='userassessmentsession',
            name='resumed_at',
        ),
        migrations.AddField(
            model_name='userassessmentsession',
            name='total_incorrect_qids',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userassessmentsession',
            name='total_unanswered_qids',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='analysis_data',
            field=models.JSONField(default=dict),
        ),
    ]
