# Generated by Django 3.2.13 on 2023-03-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_auto_20230227_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessmentsession',
            name='total_answered_qids',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userassessmentsession',
            name='total_unvisited_qids',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userassessmentsession',
            name='total_visited_qids',
            field=models.JSONField(default=dict),
        ),
    ]
