# Generated by Django 3.2.13 on 2023-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_auto_20230303_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassessmentsession',
            old_name='total_attempted',
            new_name='total_answered',
        ),
        migrations.AddField(
            model_name='userassessmentsession',
            name='total_unvisited',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userassessmentsession',
            name='total_visited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
