# Generated by Django 3.2.13 on 2023-03-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_auto_20230303_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='stat',
            field=models.CharField(choices=[('ORIGIN', 'ORIGIN'), ('MIGRATED', 'MIGRATED')], default='ORIGIN', max_length=255),
        ),
    ]
