# Generated by Django 3.2.13 on 2023-03-14 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_auto_20230313_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='db.question'),
        ),
    ]
