# Generated by Django 3.2.13 on 2023-04-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_auto_20230325_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='stat',
            field=models.CharField(choices=[('ORIGIN', 'ORIGIN'), ('MIGRATED', 'MIGRATED'), ('DESKTOP', 'DESKTOP')], default='ORIGIN', max_length=255),
        ),
    ]
