# Generated by Django 3.2.13 on 2023-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_remove_user_set_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_password_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
