# Generated by Django 3.2.13 on 2023-04-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_user_set_password_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_mistake_analyzer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVED', 'ARCHIVED')], default='ACTIVE', max_length=255),
        ),
        migrations.AddField(
            model_name='userassessmentsession',
            name='is_resume_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
