# Generated by Django 3.2.13 on 2023-05-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_group_groupuser_practiceset_practicesetassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesetassessment',
            name='practice_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_set', to='db.practiceset'),
        ),
    ]
