# Generated by Django 3.2.13 on 2023-05-12 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0044_alter_practicesetassessment_practice_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AddField(
            model_name='practicesetassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicesetassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
    ]
