# Generated by Django 3.2.13 on 2023-05-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_testallocationgroupuser_testallocationlogger_testallocationpracticesetassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testallocationlogger',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='testallocationpracticesetassessment',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='testallocationpracticesetassessment',
            name='practice_set',
        ),
        migrations.RemoveField(
            model_name='testallocationpracticesetassessment',
            name='test_allocation',
        ),
        migrations.DeleteModel(
            name='TestAllocationGroupUser',
        ),
        migrations.DeleteModel(
            name='TestAllocationLogger',
        ),
        migrations.DeleteModel(
            name='TestAllocationPracticeSetAssessment',
        ),
    ]
