# Generated by Django 3.2.13 on 2023-05-12 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_auto_20230513_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAllocationLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('kind', models.CharField(choices=[('MOCK', 'MOCK'), ('SECTIONAL', 'SECTIONAL'), ('MICRO', 'MICRO'), ('PRACTICE_SHEET', 'PRACTICE_SHEET')], default='MOCK', max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='db.assessment')),
            ],
            options={
                'db_table': 'test_allocation_logger',
            },
        ),
        migrations.CreateModel(
            name='TestAllocationPracticeSetAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_allocation_set_assessment', to='db.assessment')),
                ('practice_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_allocation_practice_set', to='db.practiceset')),
                ('test_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_allocation_set', to='db.testallocationlogger')),
            ],
            options={
                'db_table': 'test_allocation_practice_set_assessment',
            },
        ),
        migrations.CreateModel(
            name='TestAllocationGroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_allocation_groups', to='db.group')),
                ('test_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_allocation_group_user', to='db.testallocationlogger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_allocation_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_allocation_group_user',
            },
        ),
    ]
