# Generated by Django 3.2.13 on 2023-05-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_testallocationgroupuser_testallocationlogger_testallocationpracticesetassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testallocationlogger',
            name='assessment',
        ),
        migrations.AddField(
            model_name='testallocationlogger',
            name='assessment',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='db.Assessment'),
        ),
    ]
