# Generated by Django 3.2.13 on 2023-05-30 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0051_user_ops_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tutors',
        ),
        migrations.AddField(
            model_name='user',
            name='english_tutors',
            field=models.ManyToManyField(blank=True, related_name='_db_user_english_tutors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='math_tutors',
            field=models.ManyToManyField(blank=True, related_name='_db_user_math_tutors_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
