# Generated by Django 3.2.13 on 2023-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0052_auto_20230530_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='sigma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='xbar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
