# Generated by Django 3.2.13 on 2023-06-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_auto_20230614_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bd_comments_enquiry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_post',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='help',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parents_comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='prep_navigation',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='school_curriculum',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='school_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='starting_scores',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
