# Generated by Django 3.2.13 on 2023-06-15 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0055_auto_20230614_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('progress', models.JSONField(blank=True, null=True)),
                ('core_class', models.IntegerField(default=0)),
                ('doubts_class', models.IntegerField(default=0)),
                ('strategy_class', models.IntegerField(default=0)),
                ('sectional_class', models.IntegerField(default=0)),
                ('reading_articles', models.IntegerField(default=0)),
                ('mock_tests', models.IntegerField(default=0)),
                ('practice_sheet', models.IntegerField(default=0)),
                ('analyse', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_progress',
            },
        ),
    ]
