# Generated by Django 3.2.13 on 2023-07-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0057_auto_20230626_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.TextField(blank=True),
        ),
    ]
