# Generated by Django 3.2.13 on 2023-08-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0059_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('school_city', models.CharField(blank=True, max_length=255)),
                ('school_state', models.CharField(blank=True, max_length=255)),
                ('school_country', models.CharField(blank=True, max_length=255)),
                ('school_curriculum', models.CharField(choices=[('ib', 'IB'), ('gcse', 'GSSE'), ('cbse', 'CBSE'), ('isc', 'ISC'), ('state_board', 'State Board'), ('american_curriculum', 'American Curriculum'), ('ap_curriculum', 'AP Curriculum'), ('level', 'Level')], default='ib', max_length=255)),
                ('school_type', models.CharField(choices=[('boarding', 'Boarding'), ('day_school', 'Day School'), ('weekly_boarding', 'Weekly Boarding')], default='boarding', max_length=255)),
            ],
            options={
                'db_table': 'db_school',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_board',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_curriculum',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_type',
        ),
    ]
