# Generated by Django 3.2.20 on 2023-09-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by_ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_by_ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_link',
            field=models.TextField(null=True),
        ),
    ]
