# Generated by Django 3.2.20 on 2023-09-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0061_auto_20230915_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
