# Generated by Django 3.2.13 on 2023-08-25 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0061_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent_1_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_1_mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_1_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_2_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_2_mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_2_name',
        ),
        migrations.AddField(
            model_name='user',
            name='counselors',
            field=models.ManyToManyField(blank=True, related_name='_db_user_counselors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_db_user_parents_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('tutor', 'Tutor'), ('typist', 'Typist'), ('manager', 'Manager'), ('prep_manager', 'Prep Manager'), ('sso_manager', 'SSO Manager'), ('parent', 'Parent'), ('counselor', 'Counselor')], default='user', max_length=64),
        ),
    ]
