# Generated by Django 3.2.20 on 2023-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_auto_20230918_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
