# Generated by Django 3.2.13 on 2023-09-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_auto_20230905_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='mega_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='db.megadomain'),
        ),
    ]
