# Generated by Django 3.2.20 on 2023-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timezone',
            field=models.CharField(max_length=50),
        ),
    ]
