# Generated by Django 3.2.13 on 2023-09-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0064_domain_mega_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='mega_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mega_domain', to='db.megadomain'),
        ),
        migrations.AddField(
            model_name='question',
            name='mega_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_mega_domain', to='db.megadomain'),
        ),
    ]
