# Generated by Django 3.2.20 on 2023-09-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0064_auto_20230918_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timezone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
