# Generated by Django 3.2.20 on 2023-09-29 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0065_alter_appointment_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('sequence', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='MotherSessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('title', models.CharField(max_length=50, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msp_subject', to='db.subject')),
            ],
            options={
                'db_table': 'session_plan',
            },
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(default='R', max_length=2)),
                ('short_desc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student_category',
            },
        ),
        migrations.CreateModel(
            name='StudentChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('sequence', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_chapters',
            },
        ),
        migrations.CreateModel(
            name='StudentModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('sequence', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50, null=True)),
                ('time', models.CharField(max_length=30, null=True)),
                ('no_of_topics', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_student', to=settings.AUTH_USER_MODEL)),
                ('student_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_chapter', to='db.studentchapters')),
            ],
            options={
                'db_table': 'student_modules',
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_subject', to='db.subject'),
        ),
        migrations.CreateModel(
            name='StudentTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('sequence', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50, null=True)),
                ('data', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_student', to=settings.AUTH_USER_MODEL)),
                ('student_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_student_module', to='db.studentmodules')),
            ],
            options={
                'db_table': 'student_topics',
            },
        ),
        migrations.CreateModel(
            name='StudentSessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('mother_session_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssp_student_session_plan', to='db.mothersessionplan')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssp_student', to=settings.AUTH_USER_MODEL)),
                ('student_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssp_student_category', to='db.studentcategory')),
            ],
            options={
                'db_table': 'student_session_plan',
            },
        ),
        migrations.AddField(
            model_name='studentchapters',
            name='student_session_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_student_session_plan', to='db.studentsessionplan'),
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('sequence', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=20, null=True)),
                ('no_of_topics', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('time', models.CharField(max_length=10, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_chapter', to='db.chapters')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='ModuleCategoryTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('time', models.CharField(max_length=30, null=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mct_module', to='db.modules')),
                ('student_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mct_student_category', to='db.studentcategory')),
            ],
            options={
                'db_table': 'module_category_time',
            },
        ),
        migrations.CreateModel(
            name='ChapterTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('sequence', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50, null=True)),
                ('data', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ct_module', to='db.modules')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.AddField(
            model_name='chapters',
            name='mother_session_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_session_plan', to='db.mothersessionplan'),
        ),
    ]
