# Generated by Django 3.2.20 on 2023-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0066_auto_20230929_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
