# Generated by Django 3.2.20 on 2023-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0067_auto_20230913_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('tutor', 'Tutor'), ('typist', 'Typist'), ('manager', 'Manager'), ('prep_manager', 'Prep Manager'), ('sso_manager', 'SSO Manager'), ('parent', 'Parent'), ('counselor', 'Counselor'), ('user_manager', 'User Manager')], default='user', max_length=64),
        ),
    ]
