# Generated by Django 3.2.20 on 2023-10-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0068_megadomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megadomain',
            name='domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='mega_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='db.megadomain'),
        ),
        migrations.AddField(
            model_name='megadomain',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='megadomains', to='db.subject'),
        ),
    ]
