# Generated by Django 3.2.20 on 2024-01-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0068_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('school_name',)},
        ),
    ]
