# Generated by Django 3.2.20 on 2024-03-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0070_auto_20240215_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_sessions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='context',
            field=models.CharField(choices=[('library', 'Library'), ('exams', 'Exams'), ('subjects', 'Subjects'), ('users', 'users'), ('sessions', 'sessions')], default='library', max_length=255),
        ),
    ]
