# Generated by Django 3.2.20 on 2024-03-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0071_auto_20240305_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ptm_date',
            field=models.DateField(null=True),
        ),
    ]
