# Generated by Django 3.2.20 on 2023-10-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0071_domain_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategory',
            name='baseline_score',
            field=models.CharField(default='<550', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super', 'Super'), ('admin', 'Admin'), ('user', 'User'), ('tutor', 'Tutor'), ('typist', 'Typist'), ('manager', 'Manager')], default='user', max_length=64),
        ),
    ]
