# Generated by Django 3.2.20 on 2023-10-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0072_auto_20231006_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategory',
            name='ca',
            field=models.CharField(choices=[('2ca', '2 CA'), ('3ca', '3 CA'), ('4ca', '4 CA')], default='2ca', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcategory',
            name='category',
            field=models.CharField(choices=[('r', 'R'), ('s', 'S'), ('t', 'T')], default='r', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcategory',
            name='ha',
            field=models.CharField(choices=[('5ha', '5 HA'), ('6ha', '6 HA'), ('7ha', '7 HA')], default='5ha', max_length=20),
        ),
    ]
