# Generated by Django 3.2.20 on 2023-10-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0073_auto_20231006_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='studentcategory',
            name='name',
            field=models.CharField(choices=[('r', 'R'), ('s', 'S'), ('t', 'T')], default='r', max_length=20),
        ),
    ]
