# Generated by Django 3.2.20 on 2024-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0073_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('tutor', 'Tutor'), ('typist', 'Typist'), ('manager', 'Manager'), ('prep_manager', 'Prep Manager'), ('sso_manager', 'SSO Manager'), ('parent', 'Parent'), ('counselor', 'Counselor'), ('user_manager', 'User Manager'), ('guest', 'Guest'), ('hod_reading', 'HOD Reading'), ('hod_writing', 'HOD Writing'), ('hod_math', 'HOD Math')], default='guest', max_length=64),
        ),
    ]
