# Generated by Django 3.2.20 on 2023-10-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0074_auto_20231006_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategory',
            name='difficulty',
            field=models.CharField(default='5', max_length=20),
        ),
    ]
