# Generated by Django 3.2.20 on 2024-04-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0074_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_classes',
            field=models.JSONField(null=True),
        ),
    ]
