# Generated by Django 3.2.20 on 2024-04-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0075_user_pending_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='calculator',
            field=models.CharField(choices=[('', ''), ('yes', 'yes'), ('no', 'no')], default='', max_length=255),
        ),
    ]
