# Generated by Django 3.2.20 on 2023-10-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0075_studentcategory_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='r_time',
            field=models.CharField(default='30', max_length=20),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='s_time',
            field=models.CharField(default='20', max_length=20),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='t_time',
            field=models.CharField(default='15', max_length=20),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='db.subtopic')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'agendas',
            },
        ),
    ]
