# Generated by Django 3.2.20 on 2023-10-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0076_auto_20231006_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='topic',
            new_name='sub_topic',
        ),
        migrations.AlterModelTable(
            name='agenda',
            table='agenda',
        ),
    ]
