# Generated by Django 3.2.20 on 2023-10-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0077_auto_20231006_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='sub_topic',
            new_name='subtopic',
        ),
    ]
