# Generated by Django 3.2.20 on 2024-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0078_auto_20240508_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ptm_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_classes',
            field=models.JSONField(null=True),
        ),
    ]
