# Generated by Django 3.2.20 on 2024-05-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0079_auto_20240509_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsessionplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
