# Generated by Django 3.2.20 on 2024-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0079_auto_20240509_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsessionplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
