# Generated by Django 3.2.20 on 2024-05-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0080_auto_20240517_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='event_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
