# Generated by Django 3.2.20 on 2024-05-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0080_studentsessionplan_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], max_length=20, null=True),
        ),
    ]
