# Generated by Django 3.2.20 on 2024-05-22 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0081_appointments_event_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReadingCpeaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('type', models.CharField(default='Reading', max_length=80)),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value_reponse', models.CharField(max_length=255)),
                ('meta_value_domain', models.CharField(max_length=255)),
                ('meta_value_subtopic', models.CharField(max_length=255)),
                ('meta_value_score', models.IntegerField(default=0)),
                ('meta_value_skil_tested', models.CharField(max_length=255)),
                ('mega_domain', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.megadomain')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_reading_cpea',
            },
        ),
    ]
