# Generated by Django 3.2.20 on 2023-10-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0081_auto_20231006_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mothersessionplan',
            name='megadomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_plan', to='db.megadomain'),
        ),
        migrations.AlterField(
            model_name='mothersessionplan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_plan', to='db.subject'),
        ),
    ]
