# Generated by Django 3.2.20 on 2024-05-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0082_studentreadingcpeareport'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreport',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentreport',
            name='reason',
            field=models.CharField(choices=[('TUTOR_NOT_JOINED', 'Tutor_not_joined'), ('STUDENT_NOT_JOINED', 'Student_not_joined'), ('CANCEL', 'Cancel'), ('RESCHEDULE', 'Reshedule'), ('BOTH_TUTOR_AND_STUDENT_NOT_JOIN', 'Both_tutor_and_student_not_join'), ('BOTH_TUTOR_AND_STUDENT_JOIN', 'Both_tutor_and_student_join')], max_length=100),
        ),
    ]
