# Generated by Django 3.2.20 on 2023-10-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0082_auto_20231006_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotherSessionPlan',
        ),
    ]
