# Generated by Django 3.2.20 on 2024-05-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0083_auto_20240523_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreadingcpeareport',
            name='appointment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.appointments'),
        ),
        migrations.AddField(
            model_name='studentreadingcpeareport',
            name='remedial_action',
            field=models.CharField(default='nukk', max_length=255),
            preserve_default=False,
        ),
    ]
