# Generated by Django 3.2.20 on 2023-10-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0083_delete_mothersessionplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
