# Generated by Django 3.2.20 on 2024-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0084_auto_20240523_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreadingcpeareport',
            name='meta_key',
            field=models.CharField(default='default_key', max_length=255),
        ),
    ]
