# Generated by Django 3.2.20 on 2024-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0085_alter_studentreadingcpeareport_meta_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreadingcpeareport',
            name='meta_value_score',
            field=models.CharField(max_length=15),
        ),
    ]
