# Generated by Django 3.2.20 on 2024-05-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0086_alter_studentreadingcpeareport_meta_value_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreadingcpeareport',
            name='description',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
