# Generated by Django 3.2.20 on 2023-10-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0086_auto_20231006_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
