# Generated by Django 3.2.20 on 2023-11-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0088_auto_20231030_1304"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentquestion",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assignmentquestion",
            name="remarks",
            field=models.TextField(blank=True),
        ),
    ]
