# Generated by Django 3.2.20 on 2023-11-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0089_auto_20231123_1051"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentquestion",
            name="description",
        ),
        migrations.RemoveField(
            model_name="assignmentquestion",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="questionoption",
            name="description",
        ),
    ]
