# Generated by Django 3.2.20 on 2023-11-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0090_alter_user_school'),
        ('db', '0090_auto_20231123_1237'),
    ]

    operations = [
    ]
