# Generated by Django 3.2.20 on 2023-11-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0091_alter_user_school'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='day_schedule_user_id',
        #     field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        # ),
    ]
