# Generated by Django 3.2.20 on 2023-11-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0092_user_day_schedule_user_id'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='user',
        #     name='day_schedule_user_id',
        #     field=models.CharField(blank=True, max_length=255, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='school',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='db.school'),
        # ),
    ]
