# Generated by Django 3.2.20 on 2023-11-28 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0093_auto_20231128_2318'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='day_schedule_user_id',
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='day_schedule_user_id',
        #     field=models.ManyToManyField(blank=True, related_name='_db_user_day_schedule_user_id_+', to=settings.AUTH_USER_MODEL),
        # ),
    ]
