# Generated by Django 3.2.20 on 2023-11-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_auto_20231128_2328'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='day_schedule_user_id',
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='day_schedule_user_id',
        #     field=models.CharField(blank=True, max_length=255, unique=True),
        # ),
    ]
