# Generated by Django 3.2.20 on 2023-11-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0091_merge_0090_alter_user_school_0090_auto_20231123_1237'),
        ('db', '0095_auto_20231128_2339'),
    ]

    operations = [
    ]
