# Generated by Django 3.2.20 on 2023-11-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0096_merge_20231129_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_schedule_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        # migrations.AlterField(
        #     # model_name='user',
        #     # name='school',
        #     # field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='db.school'),
        # ),
    ]
