# Generated by Django 3.2.20 on 2023-11-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0098_alter_user_school'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='user',
        #     name='school',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='db.school'),
        # ),
    ]
