# Generated by Django 3.2.20 on 2023-11-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0099_alter_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('invitee_name', models.CharField(max_length=255)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('start_at', models.DateTimeField()),
                ('resource_id', models.IntegerField()),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='school',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='db.school'),
        # ),
    ]
