# Generated by Django 3.2.20 on 2023-11-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0100_auto_20231130_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invitee_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='resource_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_at',
            field=models.CharField(max_length=100, null=True),
        ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='school',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='db.school'),
        # ),
    ]
