# Generated by Django 3.2.20 on 2023-11-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0101_auto_20231130_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invitee_id',
            field=models.CharField(max_length=100, null=True),
        ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='school',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='db.school'),
        # ),
    ]
