# Generated by Django 3.2.20 on 2023-11-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0102_auto_20231130_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invitee_id',
            field=models.IntegerField(default=0),
        ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='school',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='db.school'),
        # ),
    ]
