# Generated by Django 3.2.20 on 2023-12-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0105_auto_20231205_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='attendees',
            name='attendee',
        ),
        migrations.AddField(
            model_name='appointments',
            name='booking',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Attendees',
        ),
    ]
