# Generated by Django 3.2.20 on 2023-12-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0106_auto_20231205_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='booking',
        ),
    ]
