# Generated by Django 3.2.20 on 2023-12-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_remove_appointments_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='booking',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
