# Generated by Django 3.2.20 on 2023-12-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0109_molecule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking',
            field=models.IntegerField(default=0),
        ),
    ]
