# Generated by Django 3.2.20 on 2023-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0110_booking_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
