# Generated by Django 3.2.20 on 2023-12-06 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0111_alter_booking_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='email',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='invitee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointments',
            name='invitee_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='resource',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
