# Generated by Django 3.2.20 on 2023-12-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0113_rename_email_appointments_invitee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='end_time',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='invitee',
            new_name='invitee_id',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='resource',
            new_name='resource_id',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='start_time',
            new_name='start_at',
        ),
    ]
