# Generated by Django 3.2.20 on 2023-12-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0114_auto_20231206_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='invitee_email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
