# Generated by Django 3.2.20 on 2023-12-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_alter_appointments_invitee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='ds_host_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
