# Generated by Django 3.2.20 on 2023-12-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0116_appointments_ds_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='molecule_topic_subtopic_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MoleculeTopicSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecule_id', to='db.molecule')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_id', to='db.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_id', to='db.topic')),
            ],
            options={
                'verbose_name': 'MoleculeTopicSubtopic',
                'verbose_name_plural': 'MoleculeTopicSubtopics',
                'db_table': 'molecule_topic_subtopic',
            },
        ),
    ]
