# Generated by Django 3.2.20 on 2023-12-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0118_remove_molecule_molecule_topic_subtopic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='db.domain'),
        ),
    ]
