# Generated by Django 3.2.20 on 2023-12-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_alter_subtopic_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='db.subject'),
        ),
    ]
