# Generated by Django 3.2.20 on 2023-12-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_domain_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='host_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
