# Generated by Django 3.2.20 on 2023-12-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_assignment_molecule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moleculetopicsubtopic',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_id', to='db.subtopic'),
        ),
        migrations.AlterField(
            model_name='moleculetopicsubtopic',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_id', to='db.topic'),
        ),
    ]
