# Generated by Django 3.2.20 on 2023-12-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_auto_20231212_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moleculetopicsubtopic',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moleculetopicsubtopic_id', to='db.molecule'),
        ),
        migrations.AlterField(
            model_name='moleculetopicsubtopic',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moleculetopicsubtopic_id', to='db.subtopic'),
        ),
        migrations.AlterField(
            model_name='moleculetopicsubtopic',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moleculetopicsubtopic_id', to='db.topic'),
        ),
    ]
