# Generated by Django 3.2.20 on 2023-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_auto_20231212_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutor_type',
            field=models.CharField(choices=[('english', 'English'), ('math', 'Math')], default='english', max_length=64),
        ),
    ]
