# Generated by Django 3.2.20 on 2023-12-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_user_tutor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='r_time',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='s_time',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='t_time',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
