# Generated by Django 3.2.20 on 2023-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_auto_20231214_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
