# Generated by Django 3.2.20 on 2023-12-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_molecule_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherSessionMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('molecule', models.ManyToManyField(blank=True, related_name='molecule_id', to='db.Molecule')),
                ('motherSession', models.ManyToManyField(blank=True, related_name='mother_Session_id', to='db.SessionPlan')),
            ],
            options={
                'verbose_name': 'MotherSessionMolecule',
                'verbose_name_plural': 'MotherSessionMolecules',
                'db_table': 'mother_session_molecule',
            },
        ),
    ]
