# Generated by Django 3.2.20 on 2023-12-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_mothersessionmolecule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotherSessionMolecule',
        ),
    ]
