# Generated by Django 3.2.20 on 2023-12-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_delete_mothersessionmolecule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherSessionMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('SessionPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_Session_id', to='db.sessionplan')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_id', to='db.molecule')),
            ],
            options={
                'verbose_name': 'MotherSessionMolecule',
                'verbose_name_plural': 'MotherSessionMolecules',
                'db_table': 'mother_session_molecule',
            },
        ),
    ]
