# Generated by Django 3.2.20 on 2023-12-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_mothersessionmolecule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mothersessionmolecule',
            old_name='SessionPlan',
            new_name='sessionPlan',
        ),
    ]
