# Generated by Django 3.2.20 on 2023-12-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0132_rename_sessionplan_mothersessionmolecule_sessionplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mothersessionmolecule',
            old_name='sessionPlan',
            new_name='session_plan',
        ),
    ]
