# Generated by Django 3.2.20 on 2023-12-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_rename_sessionplan_mothersessionmolecule_session_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mothersessionmolecule',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_session_molecule_id', to='db.molecule'),
        ),
        migrations.AlterField(
            model_name='mothersessionmolecule',
            name='session_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_session_molecule_id', to='db.sessionplan'),
        ),
    ]
