# Generated by Django 3.2.20 on 2023-12-22 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0136_auto_20231219_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mothersessionmolecule',
            name='molecule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_session_molecule_id', to='db.molecule'),
        ),
        migrations.AlterField(
            model_name='mothersessionmolecule',
            name='session_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_session_molecule_id', to='db.sessionplan'),
        ),
    ]
