# Generated by Django 3.2.20 on 2023-12-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0137_auto_20231222_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='megadomain',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='module',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='molecule',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='assignment',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('HOME', 'HOME'), ('CLASS', 'CLASS'), ('PRACTICE_SHEET', 'PRACTICE_SHEET')], default='PRACTICE_SHEET', max_length=255),
        ),
    ]
