# Generated by Django 3.2.20 on 2023-12-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0138_auto_20231227_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='practice_sheet',
            field=models.URLField(blank=True, null=True),
        ),
    ]
