# Generated by Django 3.2.20 on 2023-12-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0141_remove_assignment_pdf_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='subtopic',
            new_name='subTopic',
        ),
    ]
