# Generated by Django 3.2.20 on 2024-01-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0142_rename_subtopic_assignment_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='enter_your_answer',
            field=models.TextField(blank=True),
        ),
    ]
