# Generated by Django 3.2.20 on 2024-01-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0144_alter_assignmentquestion_enter_your_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='enter_your_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
