# Generated by Django 3.2.20 on 2024-01-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0146_alter_assignmentquestion_enter_your_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='question',
            new_name='questions',
        ),
    ]
