# Generated by Django 3.2.20 on 2024-01-18 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0147_rename_question_questionoption_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('school_name',)},
        ),
        migrations.CreateModel(
            name='StudentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('black_out_start_date', models.DateField(null=True)),
                ('black_out_end_date', models.DateField(null=True)),
                ('accelerator_start_date', models.DateField(null=True)),
                ('accelerator_end_date', models.DateField(null=True)),
                ('target_test_date', models.DateField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_availability',
            },
        ),
    ]
