# Generated by Django 3.2.20 on 2024-01-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0148_auto_20240118_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentavailability',
            old_name='accelerator_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='studentavailability',
            old_name='accelerator_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='studentavailability',
            old_name='black_out_end_date',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='studentavailability',
            name='black_out_start_date',
        ),
    ]
