# Generated by Django 3.2.20 on 2024-01-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0149_auto_20240119_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentavailability',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
