# Generated by Django 3.2.20 on 2024-01-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0150_alter_studentavailability_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentavailability',
            old_name='target_test_date',
            new_name='target_test_date_1',
        ),
        migrations.AddField(
            model_name='studentavailability',
            name='target_test_date_2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentavailability',
            name='target_test_date_3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentavailability',
            name='target_test_date_4',
            field=models.DateField(null=True),
        ),
    ]
