# Generated by Django 3.2.20 on 2024-01-19 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0151_auto_20240119_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentavailability',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
