# Generated by Django 3.2.20 on 2024-01-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0152_alter_studentavailability_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
