# Generated by Django 3.2.20 on 2024-01-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0155_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubtopic',
            name='practice_sheet',
            field=models.URLField(blank=True, null=True),
        ),
    ]
