# Generated by Django 3.2.20 on 2024-01-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0156_studentsubtopic_practice_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='db.domain'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='megadomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='db.megadomain'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='db.module'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='db.subject'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='db.subtopic'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='db.topic'),
        ),
    ]
