# Generated by Django 3.2.20 on 2024-01-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0154_auto_20240120_1242'),
        ('db', '0157_auto_20240122_1129'),
    ]

    operations = [
    ]
