# Generated by Django 3.2.20 on 2024-01-22 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0158_merge_0154_auto_20240120_1242_0157_auto_20240122_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsessionplan',
            name='corePrep',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentsessionplan',
            name='targetTest',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentavailability',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_availablity', to=settings.AUTH_USER_MODEL),
        ),
    ]
