# Generated by Django 3.2.20 on 2024-01-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0159_auto_20240122_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdomain',
            name='student_module',
        ),
        migrations.AddField(
            model_name='studentdomain',
            name='student_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_session', to='db.studentsessionplan'),
        ),
    ]
