# Generated by Django 3.2.20 on 2024-01-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0161_auto_20240123_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='english_student_category',
            new_name='english_category',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='math_student_category',
            new_name='math_category',
        ),
    ]
