# Generated by Django 3.2.20 on 2024-01-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0162_auto_20240123_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnglishStudentCategory',
            new_name='EnglishCategory',
        ),
        migrations.RenameModel(
            old_name='MathStudentCategory',
            new_name='MathCategory',
        ),
        migrations.AlterModelTable(
            name='englishcategory',
            table='english_category',
        ),
        migrations.AlterModelTable(
            name='mathcategory',
            table='math_category',
        ),
    ]
