# Generated by Django 3.2.20 on 2024-01-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0163_auto_20240123_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='english_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='english_category', to='db.englishcategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='math_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='math_category', to='db.mathcategory'),
        ),
    ]
