# Generated by Django 3.2.20 on 2024-01-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0167_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent')], default='parent', max_length=255),
        ),
    ]
