# Generated by Django 3.2.20 on 2024-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0168_alter_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tutor_type',
            field=models.CharField(choices=[('english', 'English'), ('math', 'Math'), ('english_reading', 'English_Reading'), ('english_writing', 'English_Writing')], default='english', max_length=64),
        ),
    ]
