# Generated by Django 3.2.20 on 2024-01-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0170_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentavailability',
            name='core_prep_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('tutor', 'Tutor'), ('typist', 'Typist'), ('manager', 'Manager'), ('prep_manager', 'Prep Manager'), ('sso_manager', 'SSO Manager'), ('ops_manager', 'Ops Manager'), ('parent', 'Parent'), ('counselor', 'Counselor')], default='user', max_length=64),
        ),
    ]
