# Generated by Django 3.2.20 on 2024-01-25 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0171_auto_20240125_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='english_reading',
            field=models.ManyToManyField(blank=True, related_name='_db_user_english_reading_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='english_writing',
            field=models.ManyToManyField(blank=True, related_name='_db_user_english_writing_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
