# Generated by Django 3.2.20 on 2024-01-25 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0172_auto_20240125_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='english_reading',
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_writing',
        ),
        migrations.AddField(
            model_name='user',
            name='english_reading_tutors',
            field=models.ManyToManyField(blank=True, related_name='_db_user_english_reading_tutors_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='english_writing_tutors',
            field=models.ManyToManyField(blank=True, related_name='_db_user_english_writing_tutors_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
