# Generated by Django 3.2.20 on 2024-02-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0174_appointmentmolecule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmolecule',
            old_name='student_id',
            new_name='student',
        ),
    ]
