# Generated by Django 3.2.20 on 2024-02-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0175_rename_student_id_appointmentmolecule_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmolecule',
            name='student',
        ),
        migrations.AddField(
            model_name='appointmentmolecule',
            name='molecule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='molecule', to='db.molecule'),
        ),
    ]
