# Generated by Django 3.2.20 on 2024-02-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0178_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='db.appointments'),
        ),
    ]
