# Generated by Django 3.2.20 on 2024-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0180_alter_feedback_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
