# Generated by Django 3.2.20 on 2024-02-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0182_auto_20240210_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignmentquestion',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='studentassignmentquestion',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
