# Generated by Django 3.2.20 on 2024-02-12 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0183_auto_20240210_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], default='student', max_length=64)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_questions', to='db.question')),
            ],
            options={
                'db_table': 'feedback_questions',
            },
        ),
    ]
