# Generated by Django 3.2.20 on 2024-02-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0184_feedbackquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackquestions',
            name='question',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
