# Generated by Django 3.2.20 on 2024-02-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0185_alter_feedbackquestions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ratings',
        ),
        migrations.CreateModel(
            name='FeedbackQuestionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('rating', models.IntegerField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ratings', to='db.feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.feedbackquestions')),
            ],
            options={
                'db_table': 'feedback_question_ratings',
            },
        ),
    ]
