# Generated by Django 3.2.20 on 2024-02-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0186_auto_20240212_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_start_date',
            field=models.DateField(null=True),
        ),
    ]
