# Generated by Django 3.2.20 on 2024-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0187_user_class_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='commenter',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
