# Generated by Django 3.2.20 on 2024-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0189_user_is_onboarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target_Test_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'target_test_dates',
            },
        ),
    ]
