# Generated by Django 3.2.20 on 2024-03-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0190_target_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='mega_doamin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
