# Generated by Django 3.2.20 on 2024-03-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0192_rename_mega_doamin_appointments_mega_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='molecule',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
