# Generated by Django 3.2.20 on 2024-03-14 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0193_auto_20240312_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CpeaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.appointments')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpea_reports', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpea_tutor_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cpea_questions',
            },
        ),
    ]
