# Generated by Django 3.2.20 on 2024-03-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0194_auto_20240314_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cpea_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
