# Generated by Django 3.2.20 on 2024-03-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0195_user_is_cpea_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cpea_enabled',
            new_name='is_cpea_eligible',
        ),
        migrations.AddField(
            model_name='user',
            name='total_class_per_day',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='total_mega_domain_class_per_day',
            field=models.IntegerField(default=1),
        ),
    ]
