# Generated by Django 3.2.20 on 2024-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0196_auto_20240319_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
