# Generated by Django 3.2.20 on 2024-03-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0197_appointments_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('HOME', 'HOME'), ('CLASS', 'CLASS'), ('PRACTICE_SHEET', 'PRACTICE_SHEET'), ('CPEA_R1', 'CPEA_R1'), ('CPEA_R2', 'CPEA_R2'), ('CPEA_R3', 'CPEA_R3'), ('CPEA_W1', 'CPEA_W1'), ('CPEA_W2', 'CPEA_W2'), ('CPEA_W3', 'CPEA_W3'), ('CPEA_M1', 'CPEA_M1'), ('CPEA_M2', 'CPEA_M2'), ('CPEA_M3', 'CPEA_M3')], default='PRACTICE_SHEET', max_length=255),
        ),
    ]
