# Generated by Django 3.2.20 on 2024-03-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0199_auto_20240321_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CpeaQuestion',
            new_name='StudnetCpeaReport',
        ),
    ]
