# Generated by Django 3.2.20 on 2024-03-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0200_rename_cpeaquestion_studnetcpeareport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studnetcpeareport',
            table='cpea_reports',
        ),
    ]
