# Generated by Django 3.2.20 on 2024-03-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0201_alter_studnetcpeareport_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudnetCpeaReport',
            new_name='StudentCpeaReport',
        ),
    ]
