# Generated by Django 3.2.20 on 2024-03-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0202_rename_studnetcpeareport_studentcpeareport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcpeareport',
            name='assignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.assignment'),
        ),
    ]
