# Generated by Django 3.2.20 on 2024-03-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0204_auto_20240327_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_english_reading_assigned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_english_writing_assigned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_math_assigned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
