# Generated by Django 3.2.20 on 2024-03-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0205_auto_20240328_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcpeareport',
            name='status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Result_Awaited', 'Result_Awaited')], default='Result_Awaited', max_length=20),
        ),
    ]
