# Generated by Django 3.2.20 on 2024-03-29 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0206_alter_studentcpeareport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('type', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=35)),
                ('sso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_class_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_classes',
            },
        ),
    ]
