# Generated by Django 3.2.20 on 2024-04-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0207_groupclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcpeareport',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterModelTable(
            name='studentcpeareport',
            table='student_cpea_reports',
        ),
        migrations.CreateModel(
            name='CpeaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('cpea_question', models.CharField(max_length=150)),
                ('mega_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpea_report_mega_domian', to='db.megadomain')),
            ],
            options={
                'verbose_name': 'CPEA Report',
                'verbose_name_plural': 'CPEA Reports',
            },
        ),
    ]
