# Generated by Django 3.2.20 on 2024-04-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0208_auto_20240401_1200'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cpeareport',
            table='cpea_reports',
        ),
    ]
