# Generated by Django 3.2.20 on 2024-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0209_alter_cpeareport_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcpeareport',
            name='overall_feedback',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
