# Generated by Django 3.2.20 on 2024-04-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0210_studentcpeareport_overall_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isRepeater',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
