# Generated by Django 3.2.20 on 2024-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0211_user_isrepeater'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpeareport',
            name='remedial_acion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
