# Generated by Django 3.2.20 on 2024-04-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0212_cpeareport_remedial_acion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpeareport',
            old_name='remedial_acion',
            new_name='remedial_action',
        ),
    ]
