# Generated by Django 3.2.18 on 2024-04-10 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0213_rename_remedial_acion_cpeareport_remedial_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='event_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentcpeareport',
            name='overall_feedback',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='TimeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('time_taken', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('type', models.CharField(choices=[('QUESTION', 'Question'), ('PRACTICE_SHEET', 'Practice_Sheet'), ('CPEA_SHEET', 'Cpea_Sheet')], max_length=20)),
                ('is_visited', models.BooleanField(default=False)),
                ('is_Answered', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_analytics_assignment', to='db.assignment')),
                ('assignment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_analytics_assignment_question', to='db.assignmentquestion')),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_analytics_question_option', to='db.questionoption')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_analytics_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
