# Generated by Django 3.2.18 on 2024-04-15 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0214_auto_20240410_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('event_id', models.CharField(max_length=100)),
                ('class_name', models.CharField(default=None, max_length=500, null=True)),
                ('tutor_name', models.CharField(max_length=100)),
                ('sso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentGroupEvents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_group_events',
            },
        ),
        migrations.DeleteModel(
            name='GroupClass',
        ),
    ]
