# Generated by Django 3.2.18 on 2024-04-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0215_auto_20240415_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupevents',
            name='is_taken',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentgroupevents',
            name='tutor',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='StudentGroupEventTutor', to='db.user'),
            preserve_default=False,
        ),
    ]
