# Generated by Django 3.2.18 on 2024-04-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0216_auto_20240415_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupevents',
            name='subject',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
    ]
