# Generated by Django 3.2.18 on 2024-04-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0217_studentgroupevents_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeanalytics',
            name='assignment_question',
        ),
        migrations.RemoveField(
            model_name='timeanalytics',
            name='question_option',
        ),
        migrations.AddField(
            model_name='timeanalytics',
            name='student_assignment_question',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='time_analytics_assignment_question', to='db.studentassignmentquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeanalytics',
            name='student_question_option',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='time_analytics_question_option', to='db.studentquestionoption'),
            preserve_default=False,
        ),
    ]
