# Generated by Django 3.2.18 on 2024-04-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0218_auto_20240416_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeanalytics',
            old_name='is_Answered',
            new_name='is_answered',
        ),
    ]
