# Generated by Django 3.2.18 on 2024-04-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0220_studentgroupevents_is_sso_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupevents',
            name='deptHead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deptHead', to='db.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroupevents',
            name='target_test_date',
            field=models.DateField(null=True),
        ),
    ]
