# Generated by Django 3.2.18 on 2024-04-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0221_auto_20240417_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupevents',
            name='group_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
