# Generated by Django 3.2.18 on 2024-04-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0222_studentgroupevents_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('is_student_joined', models.BooleanField(default=False)),
                ('is_tutor_joined', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('TUTOR_NOT_JOINED', 'Tutor_not_joined'), ('STUDENT_NOT_JOINED', 'Student_not_joined'), ('CANCEL', 'Cancel'), ('RESCHEDULE', 'Reshedule')], max_length=100)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_reports', to='db.appointments')),
            ],
            options={
                'db_table': 'appointment_reports',
            },
        ),
    ]
