# Generated by Django 3.2.18 on 2024-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0223_appointmentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='megadomain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
